import 'package:taskaway_app/features/tasks/data/models/task_model.dart';

/// Abstract class for remote data source operations related to tasks.
abstract class TaskRemoteDataSource {
  /// Fetches all tasks.
  Future<List<Task>> getTasks();

  /// Adds a new task.
  /// The [task] to be added should not have an ID, as it will be generated by the backend.
  /// It should contain the [title].
  Future<void> addTask(Task task);

  /// Updates an existing task.
  Future<void> updateTask(Task task);

  /// Deletes a task by its [id].
  Future<void> deleteTask(String id);

  /// Permanently deletes a task by its [id].
  Future<void> permanentlyDeleteTask(String id);

  /// Cleans up old deleted tasks.
  Future<void> cleanupOldDeletedTasks();
}
